server:
  port: 8081

spring:
  application:
    name: manager-service
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/fashion_manager
    username: swcamp
    password: swcamp

  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 200MB

  web:
    resources:
      #     수정 부분
      static-locations: file:///C:/3rd project/public/images/

  jpa:
    generate-ddl: false
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect
    properties:
      hibernate:
        format_sql: true

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:/mappers/**/*.xml
  type-aliases-package: fashionmanager.song.develop

token:
  expiration_time: 86400000
  secret: CxCdBy6P0vET6d/oKN9YSXzUBwfYGR+petj55jmBGrk3XaTqpaCMdgYbv7Q7ccrwjc2441jyOY0OKCFqbZPOHQ==
logging:
  level:
    fashionmanager.song.develop: debug


eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance-id}:${random.value}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/


# 수정부분
file:
  upload-root: "C:/3rdProjectFE/public/images"



